import type { ContentLanguage } from "@/types/workspace";

/** Exact or substring phrases to flag before publication (per language). */
export const BANNED_PHRASES_BY_LANG: Record<
  ContentLanguage,
  { id: string; phrase: string }[]
> = {
  fr: [
    { id: "baisser_la_friction", phrase: "baisser la friction" },
    { id: "reduire_la_friction", phrase: "réduire la friction" },
    { id: "game_changer", phrase: "game changer" },
    { id: "dans_un_monde_ou", phrase: "dans un monde où" },
    { id: "dans_un_monde", phrase: "dans un monde" },
    { id: "monde_en_constante", phrase: "monde en constante évolution" },
    { id: "ere_du_numerique", phrase: "à l'ère du numérique" },
    { id: "spoiler", phrase: "spoiler :" },
    { id: "spoiler_alert", phrase: "spoiler alert" },
    { id: "en_fin_de_compte", phrase: "en fin de compte" },
    { id: "la_cle_du_succes", phrase: "la clé du succès" },
    { id: "le_vrai_levier", phrase: "le vrai levier" },
    { id: "le_veritable_levier", phrase: "le véritable levier" },
    { id: "quand_je_creuse", phrase: "quand je creuse" },
    { id: "en_creusant", phrase: "en creusant" },
    { id: "je_vois_beaucoup_de", phrase: "je vois beaucoup de" },
    { id: "on_me_dit_souvent", phrase: "on me dit souvent" },
    { id: "phrase_que_jentends", phrase: "phrase que j'entends" },
    { id: "jentends_souvent", phrase: "j'entends souvent" },
    { id: "ce_que_jentends_souvent", phrase: "ce que j'entends souvent" },
    { id: "beaucoup_de_peu_de", phrase: "beaucoup de rendez-vous, peu de" },
    { id: "moins_de_plus_de", phrase: "moins de monde, plus de" },
    { id: "liberer_le_plein", phrase: "libérer le plein potentiel" },
    { id: "solution_innovante", phrase: "solution innovante" },
    { id: "revolutionner_votre", phrase: "révolutionner votre" },
    { id: "transformation_digitale", phrase: "transformation digitale" },
    { id: "demarche_proactive", phrase: "démarche proactive" },
    { id: "tirer_parti", phrase: "tirer parti" },
    { id: "capitaliser_sur", phrase: "capitaliser sur" },
    { id: "apporter_de_la_valeur", phrase: "apporter de la valeur" },
    { id: "niveau_superieur", phrase: "niveau supérieur" },
    { id: "penser_hors_des_sentiers", phrase: "penser hors des sentiers" },
    { id: "booster_votre", phrase: "booster votre" },
    { id: "unlock", phrase: "unlock" },
    { id: "debloquer", phrase: "débloquer" },
    { id: "plongeons", phrase: "plongeons" },
    { id: "ravi_de_partager", phrase: "ravi de partager" },
    { id: "je_suis_ravi", phrase: "je suis ravi" },
    { id: "pour_commencer", phrase: "pour commencer" },
    { id: "tout_dabord", phrase: "tout d'abord" },
    { id: "premiereement", phrase: "premièrement" },
    { id: "ce_post_traite", phrase: "ce post traite de" },
    { id: "assurez_vous_de", phrase: "assurez-vous de" },
    { id: "takeaway_cle", phrase: "takeaway clé" },
    { id: "au_final", phrase: "au final" },
    { id: "sans_further_ado", phrase: "sans further ado" },
    { id: "mindset", phrase: "mindset" },
    { id: "synergie", phrase: "synergie" },
    { id: "disruptif", phrase: "disruptif" },
    { id: "contribuer_a", phrase: "contribuer à" },
    { id: "favoriser_la", phrase: "favoriser la" },
    { id: "permet_d", phrase: "permet d'" },
    { id: "permet_de", phrase: "permet de" },
    { id: "commentez_et_ajoutez", phrase: "commentez et ajoutez" },
    { id: "ceux_qui_me_suivent", phrase: "ceux qui me suivent peuvent" },
    { id: "bon_reseau_ne_se_mesure", phrase: "bon réseau ne se mesure" },
    { id: "je_perfectionne", phrase: "je perfectionne" },
    { id: "ce_qui_m_interesse_vraiment", phrase: "ce qui m'intéresse vraiment" },
  ],
  en: [
    { id: "lower_friction", phrase: "lower the friction" },
    { id: "reduce_friction", phrase: "reduce friction" },
    { id: "game_changer", phrase: "game changer" },
    { id: "in_todays_world", phrase: "in today's world" },
    { id: "in_a_world_where", phrase: "in a world where" },
    { id: "fast_paced_world", phrase: "fast-paced world" },
    { id: "dynamic_landscape", phrase: "dynamic landscape" },
    { id: "spoiler", phrase: "spoiler:" },
    { id: "spoiler_alert", phrase: "spoiler alert" },
    { id: "at_the_end_of_the_day", phrase: "at the end of the day" },
    { id: "the_key_to_success", phrase: "the key to success" },
    { id: "the_real_lever", phrase: "the real lever" },
    { id: "when_i_dig", phrase: "when i dig" },
    { id: "digging_a_bit", phrase: "digging a bit" },
    { id: "i_see_a_lot_of", phrase: "i see a lot of" },
    { id: "i_often_hear", phrase: "i often hear" },
    { id: "phrase_i_often_hear", phrase: "phrase i often hear" },
    { id: "phrase_i_hear", phrase: "phrase i hear" },
    { id: "what_i_often_hear", phrase: "what i often hear" },
    { id: "lots_of_few", phrase: "lots of meetings, few" },
    { id: "fewer_more_value", phrase: "fewer people, more" },
    { id: "unlock_full_potential", phrase: "unlock the full potential" },
    { id: "empower_your_team", phrase: "empower your team" },
    { id: "future_proof", phrase: "future-proof" },
    { id: "seamless_experience", phrase: "seamless experience" },
    { id: "cutting_edge", phrase: "cutting-edge" },
    { id: "next_level", phrase: "to the next level" },
    { id: "think_outside_the_box", phrase: "think outside the box" },
    { id: "unlock", phrase: "unlock" },
    { id: "leverage", phrase: "leverage" },
    { id: "utilize", phrase: "utilize" },
    { id: "delve", phrase: "delve" },
    { id: "lets_delve", phrase: "let's delve" },
    { id: "excited_to_share", phrase: "excited to share" },
    { id: "key_takeaway", phrase: "key takeaway" },
    { id: "heres_the_thing", phrase: "here's the thing" },
    { id: "without_further_ado", phrase: "without further ado" },
    { id: "first_and_foremost", phrase: "first and foremost" },
    { id: "to_begin_with", phrase: "to begin with" },
    { id: "testament", phrase: "testament" },
    { id: "beacon", phrase: "beacon" },
    { id: "tapestry", phrase: "tapestry" },
    { id: "pivotal", phrase: "pivotal" },
    { id: "underscore", phrase: "underscore" },
    { id: "paramount", phrase: "paramount" },
    { id: "journey_metaphor", phrase: "our journey" },
    { id: "revolutionary", phrase: "revolutionary" },
    { id: "game_changing", phrase: "game-changing" },
    { id: "mindset", phrase: "mindset" },
    { id: "synergy", phrase: "synergy" },
    { id: "disruptive", phrase: "disruptive" },
    { id: "enables_you", phrase: "enables you" },
    { id: "foster", phrase: "foster" },
    { id: "facilitate", phrase: "facilitate" },
    { id: "ensures_that", phrase: "ensures that" },
    { id: "comment_and_connect", phrase: "comment and connect" },
    { id: "those_who_follow_me", phrase: "those who follow me can" },
    { id: "good_network_isnt_measured", phrase: "good network isn't measured" },
    { id: "im_perfecting", phrase: "i'm perfecting" },
    { id: "what_i_really_care_about", phrase: "what i really care about" },
  ],
  es: [
    { id: "reducir_la_friccion", phrase: "reducir la fricción" },
    { id: "game_changer", phrase: "game changer" },
    { id: "en_un_mundo_donde", phrase: "en un mundo donde" },
    { id: "en_el_mundo_actual", phrase: "en el mundo actual" },
    { id: "entorno_constante", phrase: "entorno actual en constante" },
    { id: "spoiler", phrase: "spoiler:" },
    { id: "al_final_del_dia", phrase: "al final del día" },
    { id: "la_clave_del_exito", phrase: "la clave del éxito" },
    { id: "la_verdadera_palanca", phrase: "la verdadera palanca" },
    { id: "cuando_indago", phrase: "cuando indago" },
    { id: "al_indagar", phrase: "al indagar" },
    { id: "veo_a_muchos", phrase: "veo a muchos" },
    { id: "a_menudo_escucho", phrase: "a menudo escucho" },
    { id: "frase_que_escucho", phrase: "frase que escucho" },
    { id: "lo_que_mas_escucho", phrase: "lo que más escucho" },
    { id: "menos_mas_packaging", phrase: "menos ruido, más" },
    { id: "potenciar_al_maximo", phrase: "potenciar al máximo" },
    { id: "impulsar_tu_negocio", phrase: "impulsar tu negocio" },
    { id: "siguiente_nivel", phrase: "siguiente nivel" },
    { id: "experiencia_sin_fricciones", phrase: "experiencia sin fricciones" },
    { id: "aprovechar_al_maximo", phrase: "aprovechar al máximo" },
    { id: "pensar_fuera_de_la_caja", phrase: "pensar fuera de la caja" },
    { id: "unlock", phrase: "unlock" },
    { id: "profundicemos", phrase: "profundicemos" },
    { id: "emocionado_de_compartir", phrase: "emocionado de compartir" },
    { id: "conclusion_clave", phrase: "conclusión clave" },
    { id: "para_empezar", phrase: "para empezar" },
    { id: "en_la_era_digital", phrase: "en la era digital" },
    { id: "agendar_una", phrase: "agendar una" },
    { id: "mindset", phrase: "mindset" },
    { id: "sinergia", phrase: "sinergia" },
    { id: "disruptivo", phrase: "disruptivo" },
    { id: "fomentar", phrase: "fomentar" },
    { id: "garantizar", phrase: "garantizar" },
    { id: "permite_que", phrase: "permite que" },
    { id: "comenta_y_agregame", phrase: "comenta y agrégame" },
    { id: "dejame_un_comentario", phrase: "déjame un comentario" },
    { id: "pueden_dar_fe", phrase: "pueden dar fe" },
    { id: "buena_red_no_se_mide", phrase: "buena red no se mide" },
    { id: "estoy_perfeccionando", phrase: "estoy perfeccionando" },
    { id: "lo_que_realmente_me_interesa", phrase: "lo que realmente me interesa" },
    { id: "lista_perfil_invitacion", phrase: "lista de espera, perfil" },
  ],
};

/** Cross-language structural patterns (AI tics). */
export const STRUCTURAL_PATTERN_RULES: {
  id: string;
  re: RegExp;
  weight: number;
  maxAllowed?: number;
}[] = [
  {
    id: "not_x_its_y",
    re: /\b(ce n['']est pas|it's not|it is not|no es)\b[^.!?\n]{0,80}\b(c['']est|it's|it is|es)\b/gi,
    weight: 3,
    maxAllowed: 1,
  },
  {
    id: "triple_adjectives",
    re: /\b(\w+),\s+(\w+)\s+et\s+(\w+)\b|\b(\w+),\s+(\w+),\s+and\s+(\w+)\b|\b(\w+),\s+(\w+)\s+y\s+(\w+)\b/gi,
    weight: 2,
  },
  {
    id: "next_level_bait",
    re: /\b(pr[êe]t[e]? à passer au niveau|ready to take .{0,40}next level|list[oa] para transformar)\b/gi,
    weight: 3,
  },
];

/** Opinion / first-person markers (positive signals). */
export const OPINION_MARKERS: Record<ContentLanguage, RegExp> = {
  fr: /\b(je pense|je crois|selon moi|franchement|honnêtement|concrètement|en pratique|je ne suis pas d'accord|je m'interroge|pour moi)\b/i,
  en: /\b(i think|i believe|honestly|frankly|i'd rather|i disagree|i'm not sure|i wonder)\b/i,
  es: /\b(creo que|pienso que|honestamente|francamente|para mí|no estoy de acuerdo|me pregunto)\b/i,
};

/** First-person pronouns (je/nous, I/we, yo/nosotros). */
export const FIRST_PERSON_RE =
  /\b(je|nous|j['']|moi|I|we|my|our|yo|nosotros|nosotras)\b/i;
